#!/bin/sh

# This is global shell profile config
# It will be used by any shell for any user
# This shell should use only `sh` syntax to maximize portability,
# although it's okay to use `bash | zsh`, but this requires changing shebang

# Debug ENV (see where variable came from):
# zsh -xl 2>&1 | grep <var>

# (~) Cleanup
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CACHE_DIR="$HOME/.cache"
export XDG_DESKTOP_DIR="$HOME/Desktop"
export XDG_DOCUMENTS_DIR="$HOME/Documents"
export XDG_DOWNLOAD_DIR="$HOME/Downloads"
export XDG_MUSIC_DIR="$HOME/Music"
export XDG_PICTURES_DIR="$HOME/Pictures"
export XDG_PUBLICSHARE_DIR="$HOME/Public"
export XDG_TEMPLATES_DIR="$HOME/Templates"
export XDG_VIDEOS_DIR="$HOME/Videos"

# Default programs:
export EDITOR="nvim"
export VISUAL="neovide"
export TERM="xterm-256color"
export TERMINAL="kitty"
export BROWSER="firefox"
export ZSH_THEME=""
export NEOVIDE_MULTIGRID=true
export ZSH_DISABLE_COMPFIX=true
export SAVEHIST=10000000
export HISTFILESIZE=1000000000
export HISTSIZE=1000000000
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

# This influences ZSH autocomplete style,
# since it uses LS_COLORS
export LS_COLORS="$(dircolors -b)"

# shellcheck disable=SC2016
export VIMINIT='let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc" | source $MYVIMRC'
# shellcheck disable=SC2016
export GVIMINIT='let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc" | source $MYVIMRC'

# Wayland
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=sway
export XDG_CURRENT_DESKTOP=sway
export DESKTOP_SESSION=sway
export XKB_DEFAULT_LAYOUT=us
export LIBSEAT_BACKEND=logind
export QT_WAYLAND_DISABLE_WINDOWDECORATIONS=1
export QT_QPA_PLATFORM="wayland;xcb"
export CLUTTER_BACKEND=waylang
export MOZ_ENABLE_WAYLANG=1
export MANPAGER="sh -c 'col -bx | bat -l man -p'"

export HISTFILE="$XDG_CACHE_HOME/zhistory"
[ -f "$HISTFILE" ] || touch "$HISTFILE"

export HISTORYCONTROL="ignorespace:ignoredups"
export HISTORY_IGNORE="(git status|vi|nvim|vim|vimz|ls|cd|pwd|exit|sudo reboot|history|cd -|cd ..|exa|tree|t)"
export ZSH_COMPDUMP="$ZSH_CACHE_DIR/.zcompdump-$HOST"

export GOPATH="${XDG_DATA_HOME:-$HOME/.local/share}/go"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export PATH="$PATH:$HOME/.local/bin:$CARGO_HOME:$GOPATH/bin"

# Xorg config
export XINITRC="${XDG_CONFIG_HOME:-$HOME/.config}/x11/xinitrc"
export USERXSESSION="$XDG_CACHE_HOME/X11/xsession"
export USERXSESSIONRC="$XDG_CACHE_HOME/X11/xsessionrc"
export ALTUSERXSESSION="$XDG_CACHE_HOME/X11/Xsession"
export ERRFILE="$XDG_CACHE_HOME/X11/xsession-errors"
export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority" # This line will break some DMs.
export XSERVERRC="$XDG_CONFIG_HOME"/X11/xserverr


# Programs that require special ENV
export DOCKER_CONFIG="$XDG_CONFIG_HOME"/docker
export CONDARC="$XDG_CONFIG_HOME/conda/condarc"
export ATOM_HOME="$XDG_DATA_HOME"/atom
export AWS_SHARED_CREDENTIALS_FILE="$XDG_CONFIG_HOME"/aws/credentials
export INPUTRC="$XDG_CONFIG_HOME"/readline/inputrc
export AWS_CONFIG_FILE="$XDG_CONFIG_HOME"/aws/config
export CARGO_HOME="$XDG_DATA_HOME"/cargo
export NOTMUCH_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/notmuch-config"
export GTK2_RC_FILES="${XDG_CONFIG_HOME:-$HOME/.config}/gtk-2.0/gtkrc-2.0"
export GDBHISTFILE="$XDG_DATA_HOME"/gdb/history
export LESSHISTFILE="-"
export WGETRC="${XDG_CONFIG_HOME:-$HOME/.config}/wget/wgetrc"
export ALSA_CONFIG_PATH="$XDG_CONFIG_HOME/alsa/asoundrc"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export JUPYTER_CONFIG_DIR="$XDG_CONFIG_HOME"/jupyter
export JUPYTER_PLATFORM_DIRS="1"
export MYSQL_HISTFILE="$XDG_DATA_HOME"/mysql_history
export TERMINFO="$XDG_DATA_HOME"/terminfo
export NODE_REPL_HISTORY="$XDG_DATA_HOME"/node_repl_history
export TERMINFO_DIRS="$XDG_DATA_HOME"/terminfo:/usr/share/terminfo
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export WINEPREFIX="${XDG_DATA_HOME:-$HOME/.local/share}/wineprefixes/default"
export NUGET_PACKAGES="$XDG_CACHE_HOME"/NuGetPackages
export KODI_DATA="${XDG_DATA_HOME:-$HOME/.local/share}/kodi"
export PARALLEL_HOME="$XDG_CONFIG_HOME"/parallel
export PSQLRC="$XDG_CONFIG_HOME/pg/psqlrc"
export RIPGREP_CONFIG_PATH="$XDG_CONFIG_HOME/ripgrep/config"
export STARSHIP_CONFIG="$XDG_CONFIG_HOME"/starship.toml
export STARSHIP_CACHE="$XDG_CACHE_HOME"/starship
export VSCODE_PORTABLE="$XDG_DATA_HOME"/vscode
export PSQL_HISTORY="$XDG_STATE_HOME/psql_history"
export PSQLRC="$XDG_CONFIG_HOME/pg/psqlrc"
export PSQL_HISTORY="$XDG_STATE_HOME/psql_history"
export PGPASSFILE="$XDG_CONFIG_HOME/pg/pgpass"
export PGSERVICEFILE="$XDG_CONFIG_HOME/pg/pg_service.conf"

[ -d "$XDG_CONFIG_HOME/pg" ] || mkdir "$XDG_CONFIG_HOME/pg"

export PGPASSFILE="$XDG_CONFIG_HOME/pg/pgpass"
export PGSERVICEFILE="$XDG_CONFIG_HOME/pg/pg_service.conf"
export PASSWORD_STORE_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/password-store"
export TMUX_TMPDIR="$XDG_RUNTIME_DIR"
export WAKATIME_HOME="$XDG_CONFIG_HOME/wakatime"
export ANDROID_SDK_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/android"
export CARGO_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/cargo"
export ANSIBLE_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/ansible/ansible.cfg"
export UNISON="${XDG_DATA_HOME:-$HOME/.local/share}/unison"
export WEECHAT_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/weechat"
export MBSYNCRC="${XDG_CONFIG_HOME:-$HOME/.config}/mbsync/config"
export ELECTRUMDIR="${XDG_DATA_HOME:-$HOME/.local/share}/electrum"
# Other program settings:
export DICS="/usr/share/stardict/dic/"
export FZF_DEFAULT_OPTS="--layout=reverse --height 40%"
export QT_QPA_PLATFORMTHEME="gtk2"	# Have QT use gtk2 theme.
export MOZ_USE_XINPUT2="1"		# Mozilla smooth scrolling/touchpads.
export AWT_TOOLKIT="MToolkit wmname LG3D"	#May have to install wmname

# Start graphical server on user's current tty if not already running.
# [ "$(tty)" = "/dev/tty1" ] && exec dbus-launch --exit-with-session sway -d
