lastupdatecheck: 0
recentrepos:
- /home/posidoni/Projects/SQL_Bootcamp/Day09
- /home/posidoni/myrc
- /home/posidoni/Projects/monitoring2
startuppopupversion: 5
customcommandshistory: []
hidecommandlog: false
